### ISSUE TITLE
No solar panel was detected?

### ISSUE THREAD

**Issue by spacefan** [mjevans26/Satellite_ComputerVision#1]
When i running the app, no solar panel was detected? Is there some problem or display error?
![No solar panel was detected](https://img-blog.csdnimg.cn/2020040614240367.PNG?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NwYWNlZmFu,size_16,color_FFFFFF,t_70)

**Comment by spacefan** [comment]
Nobody, nobody, just me?

**Comment by mjevans26** [comment]
Looks like there was an error loading the predicted solar array layer - let's see if we can recreate.

**Comment by mjevans26** [comment]
@spacefan should be working now - there was a permissions issue with the underlying assets - let us know if the app continues to malfunction.

**Comment by spacefan** [comment]
> @spacefan should be working now - there was a permissions issue with the underlying assets - let us know if the app continues to malfunction.

No, the issue still exit... ->_<-

**Comment by spacefan** [comment]
> @spacefan should be working now - there was a permissions issue with the underlying assets - let us know if the app continues to malfunction.

Yes, issue resolved now! Great work!
