### ISSUE TITLE
Google earth engine；deep learning

### ISSUE THREAD

**Issue by limiao766** [mjevans26/Satellite_ComputerVision#2]
1.Hello, I am learning how to combine Google earth engine with tensorflow for windmill recognition, but I don’t know how to start? Do you have any good suggestions?
2.Is your code all written in python?

**Comment by mjevans26** [comment]
This repo should provide functionality for just that to get your started on just such a task. It works best with a GCP storage account to export and store data, but could be modified to use google drive.
It is all written in python
